remote_theme: pages-themes/architect@v0.2.0
plugins:
  - jekyll-remote-theme
title: Web Development Cheatsheets
description: Comprehensive collection of development cheatsheets
show_downloads: true
github:
  is_project_page: true
