remote_theme: pages-themes/architect@v0.2.0
plugins:
  - jekyll-remote-theme
title: The Only Cheatsheets
description: Comprehensive collection of your cheatsheets
show_downloads: true
logo: /assets/logo.png
github:
  is_project_page: true
defaults:
  - scope:
      path: ""
    values:
      head_include: |
        <link rel="shortcut icon" href="/favicon.ico" />
